spring.application.name=foneloanMini
spring.datasource.url=jdbc:mysql://localhost:3306/foneloanMini
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.hibernate.ddl-auto=update
#spring.security.user.name=user
#spring.security.user.password=user
